name: Release

on:
  push:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "chore: version packages"
          title: "chore: release new version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
